[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/products"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
