#!/usr/bin/env python3
"""
GrowFresh MPA splitter.
Reads growfresh-app.html (post Step-1, CSS already extracted) and produces:
  - shared/gf-app.js      : ALL <script> blocks concatenated
  - shared/gf-extras.css  : the 7 remaining feature-specific <style> blocks
  - shop.html, garden.html, community.html, profile.html
  - rewritten growfresh-app.html (Home + minor screens only)

Every page loads shared/gf.css + shared/gf-extras.css + shared/gf-app.js,
so every JS function/module is available everywhere. Pages only differ in
which <div class="screen"> markup they ship. switchTab() is patched to
navigate cross-page when needed.

Run from repo root:  python3 scripts/split_mpa.py
"""
import re, os, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'growfresh-app.html'
SHARED = ROOT / 'shared'
SHARED.mkdir(exist_ok=True)

# ────────── Page → screens map ──────────
PAGES = {
    'home':      ['splash','login','home','wellness','eating','learn','kids','aicoach','more'],
    'shop':      ['shop','cart','wishlist','future','upi','success'],
    'garden':    ['garden','expert','calendar','analyzer','soil','compost'],
    'community': ['community','family','familymembers'],
    'profile':   ['profile','editprofile','orders','rewards','subs','rd','rdfull'],
}
PAGE_FILE = {
    'home': 'growfresh-app.html',
    'shop': 'shop.html',
    'garden': 'garden.html',
    'community': 'community.html',
    'profile': 'profile.html',
}
SCREEN_PAGE = {s: pg for pg, lst in PAGES.items() for s in lst}

# ────────── Read source ──────────
src = SRC.read_text()
print(f"Source: {SRC} — {len(src):,} bytes, {src.count(chr(10)):,} lines")

# ────────── Extract head + shell ──────────
m = re.search(r'(<!DOCTYPE.*?</head>\s*<body>\s*)', src, flags=re.S)
HEAD = m.group(1)
post_body = src[m.end():]

m = re.search(r'(<div class="phone">\s*<div class="status-bar">.*?</div>\s*)', post_body, flags=re.S)
PHONE_OPEN = m.group(1)
rest = post_body[m.end():]

# ────────── Extract every <div class="screen" id="screen-X"> block ──────────
# Balanced-div parsing: find each "<div class=\"screen\" id=\"screen-X\">" then
# walk to matching </div>.
def extract_screen(text, start):
    """Return (screen_html, end_index) given start = index of opening tag."""
    depth = 0
    i = start
    pattern = re.compile(r'<div\b|</div>', re.IGNORECASE)
    for m in pattern.finditer(text, start):
        tok = m.group(0)
        if tok.lower() == '<div':
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                return text[start:m.end()], m.end()
    raise ValueError("unbalanced div from %d" % start)

screen_re = re.compile(r'<div class="screen" id="screen-([a-zA-Z0-9_-]+)">')
screens = {}  # id -> html
cursor = 0
non_screen_chunks = []  # markup outside screens (modals, fab, etc.) inside <body>
while True:
    m = screen_re.search(rest, cursor)
    if not m:
        non_screen_chunks.append(rest[cursor:])
        break
    non_screen_chunks.append(rest[cursor:m.start()])
    sid = m.group(1)
    html, end = extract_screen(rest, m.start())
    screens[sid] = html
    cursor = end

print(f"Screens captured: {len(screens)} — {', '.join(screens)}")

# Concatenate everything that was OUTSIDE screens (modals + scripts + styles + fab)
INTERSTITIAL = ''.join(non_screen_chunks)

# ────────── Pull out <script> and <style> blocks from interstitial ──────────
scripts = re.findall(r'<script\b[^>]*>.*?</script>', INTERSTITIAL, flags=re.S)
styles  = re.findall(r'<style\b[^>]*>.*?</style>',  INTERSTITIAL, flags=re.S)
# Remove them from interstitial to leave just modals/fab/etc.
MODALS = re.sub(r'<script\b[^>]*>.*?</script>', '', INTERSTITIAL, flags=re.S)
MODALS = re.sub(r'<style\b[^>]*>.*?</style>',   '', MODALS,      flags=re.S)
# Strip trailing </body></html>
MODALS = re.sub(r'</body>\s*</html>\s*$', '', MODALS).strip()

print(f"Scripts: {len(scripts)}, Styles: {len(styles)}, Modals length: {len(MODALS):,}")

# ────────── Build shared/gf-app.js ──────────
# Concatenate all script bodies. Each script becomes a labeled section.
js_parts = ['/* GrowFresh shared bundle — auto-generated by scripts/split_mpa.py.\n'
            '   Contains every <script> block originally inline in growfresh-app.html.\n'
            '   Loaded by: growfresh-app.html, shop.html, garden.html, community.html,\n'
            '              profile.html — every page sees every function. */\n']
for i, blk in enumerate(scripts, 1):
    body = re.sub(r'^<script\b[^>]*>', '', blk)
    body = re.sub(r'</script>$', '', body)
    js_parts.append(f"\n/* ── block {i} ─────────────────────────────────────────── */\n")
    js_parts.append(body.strip())
    js_parts.append('\n')

# ── MPA navigation patch ──────────────────────────────────────────
# Patch switchTab so that switching to a tab whose screen lives on a different
# HTML file performs a real navigation; in-page tabs still use showScreen.
nav_patch = """
/* ──────────────────────────────────────────────────────────────
   MPA NAVIGATION PATCH (split-mpa)
   Override switchTab + showScreen so that:
   • Calls for a screen present in THIS page's DOM run normally.
   • Calls for a screen on a different page navigate cross-file —
     but boot-time calls (init, goHome, applySession) are suppressed
     so the page's pre-marked primary screen stays visible.
   ────────────────────────────────────────────────────────────── */
(function(){
  var SCREEN_PAGE = %SCREEN_PAGE_JSON%;
  var PAGE_FILE   = %PAGE_FILE_JSON%;
  function fileForScreen(name){
    var pg = SCREEN_PAGE[name];
    return pg ? PAGE_FILE[pg] : null;
  }
  function here(){
    var p = (location.pathname||'').split('/').pop() || 'growfresh-app.html';
    return p;
  }
  function hasLocal(name){ return !!document.getElementById('screen-'+name); }
  // Boot guard: while true, cross-page redirects are suppressed so the
  // page's auto-marked .active screen wins. Released a tick after load.
  window.__gfBooting = true;
  window.addEventListener('load', function(){
    setTimeout(function(){ window.__gfBooting = false; }, 50);
  });
  var _origSwitchTab  = window.switchTab;
  var _origShowScreen = window.showScreen;
  window.switchTab = function(tab, cat){
    if (hasLocal(tab)) {
      if (typeof _origSwitchTab === 'function') return _origSwitchTab(tab, cat);
      if (typeof _origShowScreen === 'function') return _origShowScreen(tab);
      return;
    }
    if (window.__gfBooting) return; // ignore boot-time cross-page calls
    var file = fileForScreen(tab);
    if (file) {
      var qs = '?screen=' + encodeURIComponent(tab) + (cat ? ('&cat=' + encodeURIComponent(cat)) : '');
      location.href = file + qs;
    }
  };
  window.showScreen = function(name, opts){
    if (hasLocal(name)) {
      if (typeof _origShowScreen === 'function') return _origShowScreen(name, opts);
      return;
    }
    if (window.__gfBooting) return;
    var file = fileForScreen(name);
    if (file) location.href = file + '?screen=' + encodeURIComponent(name);
  };
  // On any page load: honour ?screen= (activates the requested screen) and ?cat=
  window.addEventListener('DOMContentLoaded', function(){
    try{
      var p = new URLSearchParams(location.search);
      var wantScreen = p.get('screen');
      var cat = p.get('cat');
      if (wantScreen && hasLocal(wantScreen)) {
        setTimeout(function(){
          if (typeof _origShowScreen === 'function') _origShowScreen(wantScreen);
        }, 80);
      }
      if (cat && here()==='shop.html') {
        setTimeout(function(){
          if (typeof _origSwitchTab === 'function') _origSwitchTab('shop', cat);
        }, 100);
      }
    }catch(e){}
  });
})();
"""
import json
nav_patch = (nav_patch
    .replace('%SCREEN_PAGE_JSON%', json.dumps(SCREEN_PAGE))
    .replace('%PAGE_FILE_JSON%',   json.dumps(PAGE_FILE)))
js_parts.append(nav_patch)

(SHARED / 'gf-app.js').write_text(''.join(js_parts))
print(f"Wrote shared/gf-app.js — {sum(len(p) for p in js_parts):,} bytes")

# ────────── Build shared/gf-extras.css ──────────
css_parts = ['/* GrowFresh extra/feature styles — auto-generated.\n'
             '   Loaded after shared/gf.css on every page. */\n']
for i, blk in enumerate(styles, 1):
    body = re.sub(r'^<style\b[^>]*>', '', blk)
    body = re.sub(r'</style>$', '', body)
    css_parts.append(f"\n/* ── style block {i} ── */\n")
    css_parts.append(body.strip())
    css_parts.append('\n')
(SHARED / 'gf-extras.css').write_text(''.join(css_parts))
print(f"Wrote shared/gf-extras.css")

# ────────── Build HTML head template ──────────
NEW_HEAD = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
<meta name="theme-color" content="#1B5E20">
<title>GrowFresh — {title}</title>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="shared/gf.css">
<link rel="stylesheet" href="shared/gf-extras.css">
</head>
<body>
'''

# Phone shell (status-bar) reused per page
SHELL = '''<div class="phone">
<div class="status-bar"><span id="status-time">9:41</span><span>GrowFresh 🌱</span><span>▲▲▲ 🔋</span></div>
'''

# Bottom nav as anchors that work cross-page; switchTab patch handles same-page taps too
def bottom_nav(active):
    items = [
      ('home',      '🏠', 'Home',      'growfresh-app.html'),
      ('shop',      '🛒', 'Shop',      'shop.html'),
      ('garden',    '🌿', 'Garden',    'garden.html'),
      ('community', '👥', 'Community', 'community.html'),
      ('profile',   '👤', 'Profile',   'profile.html'),
    ]
    parts = ['<div class="bottom-nav">']
    for tab, icon, label, href in items:
        cls = 'nav-item active' if tab==active else 'nav-item'
        parts.append(f'<a class="{cls}" href="{href}" style="text-decoration:none;color:inherit"><div class="nav-icon">{icon}</div><div class="nav-label">{label}</div></a>')
    parts.append('</div>')
    return ''.join(parts)

# Footer (scripts) per page
FOOTER = '''
</div><!-- /phone -->
%MODALS%
<script src="shared/gf-app.js"></script>
</body>
</html>
'''

# ────────── Strip ALL inline bottom-navs from captured screens ──────────
# (The page-level <div class="bottom-nav"> we render replaces them.)
def strip_inline_navs(html):
    return re.sub(r'<div class="bottom-nav">.*?</div>\s*(?=</div>\s*$|$)', '', html, flags=re.S)

# ────────── Build each new page ──────────
def page_html(pg, active_screen):
    title_map = {'home':'Home','shop':'Shop','garden':'My Garden','community':'Community','profile':'Profile'}
    parts = [NEW_HEAD.format(title=title_map[pg]), SHELL]
    for sid in PAGES[pg]:
        s = screens.get(sid, '')
        if not s:
            print(f"  ! missing screen {sid}")
            continue
        s = strip_inline_navs(s)
        # mark the primary tab screen active so it renders on first paint
        if sid == active_screen and 'class="screen active"' not in s:
            s = s.replace('<div class="screen" id="screen-'+sid+'">',
                          '<div class="screen active" id="screen-'+sid+'">', 1)
        parts.append(s)
        parts.append('\n')
    parts.append(bottom_nav(active_screen))
    parts.append(FOOTER.replace('%MODALS%', MODALS))
    return ''.join(parts)

PAGE_ACTIVE = {'home':'home','shop':'shop','garden':'garden','community':'community','profile':'profile'}

for pg in ['shop','garden','community','profile']:
    out = page_html(pg, PAGE_ACTIVE[pg])
    (ROOT / PAGE_FILE[pg]).write_text(out)
    n = out.count('\n')
    print(f"Wrote {PAGE_FILE[pg]:20s} — {len(out):,} bytes, {n:,} lines")

# Home page (rewrite growfresh-app.html with only home set)
out = page_html('home', 'home')
SRC.write_text(out)
print(f"Wrote {SRC.name:20s} — {len(out):,} bytes, {out.count(chr(10)):,} lines")

print("\nDone.")
